---
apiVersion: extensions/v1beta1
kind: Deployment
metadata:
  name: pizza-site-pink
spec:
  replicas: 1
  template:
    metadata:
      labels:
        app: web
        color: red
    spec:
      containers:
        - name: client
          image: benchtest.azurecr.io/client:red
          ports:
            - containerPort: 80
